# Unique name for this workflow
name: On push Develop - Deploy to DEV to validate

# Definition when the workflow should run
on:
    push:
        branches:
            - develop

# Jobs to be executed 01
jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
            # Checkout the code in the push event (Feature branch)
            #- name: 'Checkout source code feature branch'
            #  uses: actions/checkout@v3
            #  with:
            #    repository: 'renatocead/sfdc-scratch-pattern'
            #    fetch-depth: 0

            - name: 'Build and Deploy'
              uses: renatocead/sfdx-orgdev-build-deploy@master
              with:
                type: 'sandbox'
                certificate_path: devops/server.key.enc
                decryption_key: ${{ secrets.DECRYPTION_KEY }}
                decryption_iv: ${{ secrets.DECRYPTION_IV }}
                client_id: ${{ secrets.CONSUMER_KEY }}
                username: ${{ secrets.USER_NAME }}
                checkonly: false
                deploy_wait_time: '10'
                manifest_path: package.xml
                destructive_path: devops/destructive
                data_factory: scripts/apex/CreateBaseData.apex
                default_source_path: force-app/main/default
